[Rainmeter]
Update=-1
Author=Connect-R
BackgroundMode=2
SolidColor=0,0,0,1
DynamicWindowSize=1


[Variables]
@include=#@#Variables.inc
Scale=#DkScale#

;-------------------------------------------------------------
;-------------------------------------------------------------

[MeterIco2]
Meter=Image
ImageName=#@#Images\cross.png
X=(0*#Scale#)
Y=(0*#Scale#)
W=(19*#Scale#)
LeftMouseUpAction=[!ToggleConfig "Coastline\Dock" "Dock new.ini"][!ToggleConfig "Coastline\Dock\d1" "d1.ini"][!Update]
MouseOverAction=[!SetOption #CURRENTSECTION# ImageAlpha "80"][!ShowMeter MeterText3][!Update]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageAlpha "255"][!HideMeter MeterText2][!Update]
AntiAlias=1

[MeterRoundedRectangle]
Meter=Shape
X=(30*#Scale#)
Y=(5*#Scale#)
Shape=Rectangle 0,0,(155*#Scale#),(165*#Scale#),20 | Extend MyModifiers1
MyModifiers1=Fill Color #DkColor#,150 | StrokeWidth 0 | Stroke Color 0,0,0
Group=G1

[MeterIcon1]
Meter=Image
ImageName=#Icon1NameAndPath#
X=(15*#Scale#)r
Y=(15*#Scale#)r
W=(20*#Scale#)
LeftMouseUpAction=[#LocationPath1#][!ToggleConfig "Coastline\Dock" "Dock new.ini"][!ToggleConfig "Coastline\Dock\d1" "d1.ini"][!Update]
MouseOverAction=[!SetOption #CURRENTSECTION# ImageAlpha "80"][!Update]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageAlpha "255"][!Update]
ImageTint=#DkIconColor#
AntiAlias=1
Group=G1

[MeterIcon2]
Meter=Image
ImageName=#Icon2NameAndPath#
X=(35*#Scale#)r
Y=(0*#Scale#)r
W=(21*#Scale#)
LeftMouseUpAction=[#LocationPath2#][!ToggleConfig "Coastline\Dock" "Dock new.ini"][!ToggleConfig "Coastline\Dock\d1" "d1.ini"][!Update]
MouseOverAction=[!SetOption #CURRENTSECTION# ImageAlpha "80"][!Update]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageAlpha "255"][!Update]
ImageTint=#DkIconColor#
AntiAlias=1
Group=G1

[MeterIcon3]
Meter=Image
ImageName=#Icon3NameAndPath#
X=(35*#Scale#)r
Y=(0*#Scale#)r
W=(20*#Scale#)
LeftMouseUpAction=[#LocationPath3#][!ToggleConfig "Coastline\Dock" "Dock new.ini"][!ToggleConfig "Coastline\Dock\d1" "d1.ini"][!Update]
MouseOverAction=[!SetOption #CURRENTSECTION# ImageAlpha "80"][!Update]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageAlpha "255"][!Update]
ImageTint=#DkIconColor#
AntiAlias=1
Group=G1

[MeterIcon4]
Meter=Image
ImageName=#Icon4NameAndPath#
X=(35*#Scale#)r
Y=(0*#Scale#)r
W=(20*#Scale#)
LeftMouseUpAction=[#LocationPath4#][!ToggleConfig "Coastline\Dock" "Dock new.ini"][!ToggleConfig "Coastline\Dock\d1" "d1.ini"][!Update]
MouseOverAction=[!SetOption #CURRENTSECTION# ImageAlpha "80"][!Update]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageAlpha "255"][!Update]
ImageTint=#DkIconColor#
AntiAlias=1
Group=G1

[MeterIcon5]
Meter=Image
ImageName=#Icon5NameAndPath#
X=(-104*#Scale#)r
Y=(38*#Scale#)r
W=(20*#Scale#)
LeftMouseUpAction=[#LocationPath5#][!ToggleConfig "Coastline\Dock" "Dock new.ini"][!ToggleConfig "Coastline\Dock\d1" "d1.ini"][!Update]
MouseOverAction=[!SetOption #CURRENTSECTION# ImageAlpha "80"][!Update]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageAlpha "255"][!Update]
ImageTint=#DkIconColor#
AntiAlias=1
Group=G1

[MeterIcon6]
Meter=Image
ImageName=#Icon6NameAndPath#
X=(35*#Scale#)r
Y=(0*#Scale#)r
W=(20*#Scale#)
LeftMouseUpAction=[#LocationPath6#][!ToggleConfig "Coastline\Dock" "Dock new.ini"][!ToggleConfig "Coastline\Dock\d1" "d1.ini"][!Update]
MouseOverAction=[!SetOption MeterIcon6 ImageAlpha "80"][!Update]
MouseLeaveAction=[!SetOption MeterIcon6 ImageAlpha "255"][!Update]
ImageTint=#DkIconColor#
AntiAlias=1
Group=G1

[MeterIcon7]
Meter=Image
ImageName=#Icon7NameAndPath#
X=(35*#Scale#)r
Y=(0*#Scale#)r
W=(22*#Scale#)
LeftMouseUpAction=[#LocationPath7#][!ToggleConfig "Coastline\Dock" "Dock new.ini"][!ToggleConfig "Coastline\Dock\d1" "d1.ini"][!Update]
MouseOverAction=[!SetOption #CURRENTSECTION# ImageAlpha "80"][!Update]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageAlpha "255"][!Update]
ImageTint=#DkIconColor#
AntiAlias=1
Group=G1

[MeterIcon8]
Meter=Image
ImageName=#Icon8NameAndPath#
X=(35*#Scale#)r
Y=(0*#Scale#)r
W=(20*#Scale#)
LeftMouseUpAction=[#LocationPath8#][!ToggleConfig "Coastline\Dock" "Dock new.ini"][!ToggleConfig "Coastline\Dock\d1" "d1.ini"][!Update]
MouseOverAction=[!SetOption #CURRENTSECTION# ImageAlpha "80"][!Update]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageAlpha "255"][!Update]
ImageTint=#DkIconColor#
AntiAlias=1
Group=G1

[MeterIcon9]
Meter=Image
ImageName=#Icon9NameAndPath#
X=(-105*#Scale#)r
Y=(38*#Scale#)r
W=(20*#Scale#)
LeftMouseUpAction=[#LocationPath9#][!ToggleConfig "Coastline\Dock" "Dock new.ini"][!ToggleConfig "Coastline\Dock\d1" "d1.ini"][!Update]
MouseOverAction=[!SetOption #CURRENTSECTION# ImageAlpha "80"][!Update]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageAlpha "255"][!Update]
ImageTint=#DkIconColor#
AntiAlias=1
Group=G1

[MeterIcon10]
Meter=Image
ImageName=#Icon10NameAndPath#
X=(32*#Scale#)r
Y=(-3*#Scale#)r
W=(27*#Scale#)
LeftMouseUpAction=[#LocationPath10#][!ToggleConfig "Coastline\Dock" "Dock new.ini"][!ToggleConfig "Coastline\Dock\d1" "d1.ini"][!Update]
MouseOverAction=[!SetOption #CURRENTSECTION# ImageAlpha "80"][!Update]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageAlpha "255"][!Update]
ImageTint=#DkIconColor#
AntiAlias=1
Group=G1

[MeterIcon11]
Meter=Image
ImageName=#Icon11NameAndPath#
X=(39*#Scale#)r
Y=(0*#Scale#)r
W=(22*#Scale#)
LeftMouseUpAction=[#LocationPath11#][!ToggleConfig "Coastline\Dock" "Dock new.ini"][!ToggleConfig "Coastline\Dock\d1" "d1.ini"][!Update]
MouseOverAction=[!SetOption #CURRENTSECTION# ImageAlpha "80"][!Update]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageAlpha "255"][!Update]
ImageTint=#DkIconColor#
AntiAlias=1
Group=G1

[MeterIcon12]
Meter=Image
ImageName=#Icon12NameAndPath#
X=(35*#Scale#)r
Y=(6*#Scale#)r
W=(20*#Scale#)
LeftMouseUpAction=[#LocationPath12#][!ToggleConfig "Coastline\Dock" "Dock new.ini"][!ToggleConfig "Coastline\Dock\d1" "d1.ini"][!Update]
MouseOverAction=[!SetOption #CURRENTSECTION# ImageAlpha "80"][!Update]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageAlpha "255"][!Update]
ImageTint=#DkIconColor#
AntiAlias=1
Group=G1

[MeterIcon13]
Meter=Image
ImageName=#Icon13NameAndPath#
X=(-105*#Scale#)r
Y=(38*#Scale#)r
W=(20*#Scale#)
LeftMouseUpAction=[#LocationPath13#][!ToggleConfig "Coastline\Dock" "Dock new.ini"][!ToggleConfig "Coastline\Dock\d1" "d1.ini"][!Update]
MouseOverAction=[!SetOption #CURRENTSECTION# ImageAlpha "80"][!Update]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageAlpha "255"][!Update]
ImageTint=#DkIconColor#
AntiAlias=1
Group=G1

[MeterIcon14]
Meter=Image
ImageName=#Icon14NameAndPath#
X=(35*#Scale#)r
Y=(-2*#Scale#)r
W=(20*#Scale#)
LeftMouseUpAction=[#LocationPath14#][!ToggleConfig "Coastline\Dock" "Dock new.ini"][!ToggleConfig "Coastline\Dock\d1" "d1.ini"][!Update]
MouseOverAction=[!SetOption #CURRENTSECTION# ImageAlpha "80"][!Update]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageAlpha "255"][!Update]
ImageTint=#DkIconColor#
AntiAlias=1
Group=G1

[MeterIcon15]
Meter=Image
ImageName=#Icon15NameAndPath#
X=(31*#Scale#)r
Y=(-5*#Scale#)r
W=(30*#Scale#)
LeftMouseUpAction=[#LocationPath15#][!ToggleConfig "Coastline\Dock" "Dock new.ini"][!ToggleConfig "Coastline\Dock\d1" "d1.ini"][!Update]
MouseOverAction=[!SetOption #CURRENTSECTION# ImageAlpha "80"][!Update]
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageAlpha "255"][!Update]
ImageTint=#DkIconColor#
AntiAlias=1
Group=G1

#[MeterIcon16]
Meter=Image
ImageName=#Icon16NameAndPath#
X=(6.5*#Scale#)r
Y=(36*#Scale#)r
W=(20*#Scale#)
LeftMouseUpAction=[#LocationPath16#][!ToggleConfig "Coastline\Dock" "Dock new.ini"][!ToggleConfig "Coastline\Dock\d1" "d1.ini"][!Update]
MouseOverAction=[!SetOption MeterIcon16 ImageAlpha "80"][!ShowMeter MeterText16][!Update]
MouseLeaveAction=[!SetOption MeterIcon16 ImageAlpha "255"][!HideMeter MeterText16][!Update]
ImageTint=#DkIconColor#
AntiAlias=1
Group=G1
;-------------------------------------------------------------
;-------------------------------------------------------------


