[Variables]
opacity=255
MainLanguage=English
Language=en-US
DarkMode=1
Padding=0
redcolor=200,0,0

colorskin=40,40,40
textColor2=255,255,255
HideLabels=0
cornerRoundness=15
testerId=unreg
ProductVersion=0.2.3


Latitude=23.389500
Longitude=85.342235
Player=Spotify

RSSMain=http://feeds.bbci.co.uk/news/rss.xml

TimeFormat=%H:%M

amPmExtra=0
DisplayAMPM=1
DateLayout=%1, %2 %3

mWeather=en-CA

ThemeFont=Segoe UI




screenCornerRadius=0
scaleDpi=1
scaleDpiOthers=1
