[Variables]

██╗░░░██╗░█████╗░██████╗░██╗░█████╗░██████╗░██╗░░░░░███████╗░██████╗
██║░░░██║██╔══██╗██╔══██╗██║██╔══██╗██╔══██╗██║░░░░░██╔════╝██╔════╝
╚██╗░██╔╝███████║██████╔╝██║███████║██████╦╝██║░░░░░█████╗░░╚█████╗░
░╚████╔╝░██╔══██║██╔══██╗██║██╔══██║██╔══██╗██║░░░░░██╔══╝░░░╚═══██╗
░░╚██╔╝░░██║░░██║██║░░██║██║██║░░██║██████╦╝███████╗███████╗██████╔╝
░░░╚═╝░░░╚═╝░░╚═╝╚═╝░░╚═╝╚═╝╚═╝░░╚═╝╚═════╝░╚══════╝╚══════╝╚═════╝░


;█▀▀ █░░ █▀█ █▀▀ █▄▀   █▀ █▀▀ ▀█▀ ▀█▀ █ █▄░█ █▀▀ █▀
;█▄▄ █▄▄ █▄█ █▄▄ █░█   ▄█ ██▄ ░█░ ░█░ █ █░▀█ █▄█ ▄█

TimeScale=3
Format=I
# 'H' for 24 hr Clock and 'I' for 12 hr clock

DateScale=1.5
DayScale=1.5

CFontColor=255,255,255


;█▀▄ █▀█ █▀▀ █▄▀   █▀ █▀▀ ▀█▀ ▀█▀ █ █▄░█ █▀▀ █▀
;█▄▀ █▄█ █▄▄ █░█   ▄█ ██▄ ░█░ ░█░ █ █░▀█ █▄█ ▄█

DkScale=1.8
DkColor=255,255,255
DkIconColor=0,0,0,200

Icon1NameAndPath=#@#Images\My Computer.png
Icon1Text=My Computer
LocationPath1=Shell:::{20D04FE0-3AEA-1069-A2D8-08002B30309D}

Icon2NameAndPath=#@#Images\shutdown.png
Icon2Text=Shutdown
LocationPath2=shutdown.exe /s /t 0

Icon3NameAndPath=#@#Images\moon.png
Icon3Text=Sleep
LocationPath3=rundll32.exe powrprof.dll,SetSuspendState 0,1,0

Icon4NameAndPath=#@#Images\bin.png
Icon4Text=Recycle Bin
LocationPath4=shell:RecycleBinFolder

Icon5NameAndPath=#@#Images\settings.png
Icon5Text=Settings
LocationPath5=ms-settings:

Icon6NameAndPath=#@#Images\chrome.png
Icon6Text=Chrome
LocationPath6="#@#\Application\chrome"

Icon7NameAndPath=#@#Images\firefox.png
Icon7Text=FireFox
LocationPath7="#@#\Application\Firefox"

Icon8NameAndPath=#@#Images\Music.png
Icon8Text=Music
LocationPath8="#@#\Application\Music"

Icon9NameAndPath=#@#Images\whatsapp.png
Icon9Text=WhatsApp
LocationPath9="#@#\Application\WhatsApp"

Icon10NameAndPath=#@#Images\localsend.png
Icon10Text=LocalSend
LocationPath10="#@#\Application\LocalSend"

Icon11NameAndPath=#@#Images\weather.png
Icon11Text=Weather
LocationPath11="#@#\Application\Weather"

Icon12NameAndPath=#@#Images\YouTube.png
Icon12Text=YouTube
LocationPath12="https://www.youtube.com/"

Icon13NameAndPath=#@#Images\anime.png
Icon13Text=Anime
LocationPath13="https://www.hianime.sx"

Icon14NameAndPath=#@#Images\chatgpt.png
Icon14Text=ChatGPT
LocationPath14="https://www.chatgpt.com/"

Icon15NameAndPath=#@#Images\pw.png
Icon15Text=Physics Wallah
LocationPath15="https://www.pw.live/study/batches/study"

#Icon16NameAndPath=#@#Images\gmail.png
#Icon16Text=Gmail
#LocationPath16="https://mail.google.com/mail/u/0"




;█▄▄ ▄▀█ ▀█▀ ▀█▀ █▀▀ █▀█ █▄█   █▀ █▀▀ ▀█▀ ▀█▀ █ █▄░█ █▀▀ █▀
;█▄█ █▀█ ░█░ ░█░ ██▄ █▀▄ ░█░   ▄█ ██▄ ░█░ ░█░ █ █░▀█ █▄█ ▄█

BScale=0.9
BColor=210,223,229




;█▀▄▀█ █░█ █▀ █ █▀▀   █▀█ █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀ █▀▀ ▀█▀ ▀█▀ █ █▄░█ █▀▀ █▀
;█░▀░█ █▄█ ▄█ █ █▄▄   █▀▀ █▄▄ █▀█ ░█░ ██▄ █▀▄   ▄█ ██▄ ░█░ ░█░ █ █░▀█ █▄█ ▄█

MScale=1.4
MColor=255,255,255








████████╗██╗░░██╗███████╗  ███████╗███╗░░██╗██████╗░
╚══██╔══╝██║░░██║██╔════╝  ██╔════╝████╗░██║██╔══██╗
░░░██║░░░███████║█████╗░░  █████╗░░██╔██╗██║██║░░██║
░░░██║░░░██╔══██║██╔══╝░░  ██╔══╝░░██║╚████║██║░░██║
░░░██║░░░██║░░██║███████╗  ███████╗██║░╚███║██████╔╝
░░░╚═╝░░░╚═╝░░╚═╝╚══════╝  ╚══════╝╚═╝░░╚══╝╚═════╝░


