[Rainmeter]
Update=-1
Author=Connect-R
BackgroundMode=2
SolidColor=0,0,0,1
DynamicWindowSize=1


[Variables]
@include=#@#Variables.inc
Scale=#DkScale#

;-------------------------------------------------------------
;-------------------------------------------------------------

[MeterIco]
Meter=Image
ImageName=#@#Images\app.png
X=(0*#Scale#)
Y=(0*#Scale#)
W=(22*#Scale#)
LeftMouseUpAction=[!ToggleConfig "Coastline\Dock" "Dock new.ini"][!ToggleConfig "Coastline\Dock\d1" "d1.ini"][!Update]
MouseOverAction=[!SetOption MeterIco ImageAlpha "80"][!ShowMeter MeterTextIco][!Update]
MouseLeaveAction=[!SetOption MeterIco ImageAlpha "255"][!HideMeter MeterTextIco][!Update]
ImageTint=#DkColor#
AntiAlias=1

[MeterTextIco]
Meter=String
StringAlign=Left
StringCAse=Upper
FontFace=Roboto Slab Light
FontSize=(6*#Scale#)
FontColor=255,255,255
X=(25*#Scale#)r
Y=(6*#Scale#)r
Text="More Apps"
AntiAlias=1
DynamicVariables=1
Hidden=1